### ISSUE TITLE
icon not rendering

### ISSUE THREAD

**Issue by akzaidi** [ouseful-testing/ines-course-py-action#1]
Thanks for sharing this! I've been using gh-actions script and it has worked great.

The only issue I've found is that the icon doesn't seem to render. Even in your rendered [website](https://ouseful-testing.github.io/ines-course-py-action/) the icon in the bottom right points to: https://ouseful-testing.github.io/profile.jpg instead of https://ouseful-testing.github.io/ines-course-py-action/profile.jpg. 

This is defined in the `icon` value of `gatsby-config.js`. Is there a modification needed to ensure gh-pages doesn't link to the parent directory but the website directory?

**Comment by psychemedia** [comment]
@akzaidi Have you tried forking from the original repo? I'm nt sure to what extent this repo may be lagging the original..

**Comment by akzaidi** [comment]
yeah, i actually used ines's latest but borrowed your github actions. The local rendering of the icon seems fine, as well as publishing on netlify, so seemed specific to the gh-action.

**Comment by akzaidi** [comment]
ah got a fix, taking out the starting forward slash in https://github.com/ouseful-testing/ines-course-py-action/blob/master/src/components/layout.js#L67 fixed it. Guess that prevents gh-pages from treating that path at the top-level and instead looks for it in the relative path. thanks!
